WELL IF YOU WANNA INSULT ME AND CALL ME A TROLL THEN FINE! SCREW YOU!
I WILL SHOW ALL OF YOU THAT I AM NO TROLL! I WILL ONE DAY MAKE A HACK SO
GOOD THAT YOU'LL URINATE YOURSELFS!!!

I WILL BE BACK......... DON'T YOU FORGET IT!